- name: This sets up an httpd webserver
  hosts: all
  become: yes
  remote_user: ec2-user
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/jenkins1.pem"  
    ansible_ssh_user: "ec2-user"
  tasks:
  - name: "Install httpd"
    package:
        name:
          - "httpd"
   
